const fs = require('fs');
const path = require('path');
const source = fs.readFileSync(path.join(__dirname, '../lib/data/applysmart.ts'), 'utf8');

function parseRawCourses(source) {
  const rawStart = source.indexOf('const rawCourseInstitutionData = `');
  const rawEnd = source.indexOf('`\n\nfunction parseCourseInstitutionData', rawStart);
  if (rawStart === -1 || rawEnd === -1) {
    throw new Error('rawCourseInstitutionData not found');
  }
  const raw = source.slice(rawStart + 'const rawCourseInstitutionData = `'.length, rawEnd);
  const entryRegex = /{[\s\S]*?"course"\s*:\s*"([^\"]+)"[\s\S]*?"institutions"\s*:\s*\[([\s\S]*?)\][\s\S]*?}/g;
  const institutionRegex = /"([^\"]+)"/g;
  const map = {};
  let match;
  while ((match = entryRegex.exec(raw)) !== null) {
    const course = match[1].trim();
    const instText = match[2];
    const institutions = [];
    let instMatch;
    while ((instMatch = institutionRegex.exec(instText)) !== null) {
      institutions.push(instMatch[1].trim());
    }
    map[course] = institutions;
  }
  return map;
}

function parseAliasKeys(source) {
  const aliasStart = source.indexOf('export const courseInstitutionAliasMap: Record<string, string> = {');
  const aliasEnd = source.indexOf('};', aliasStart);
  if (aliasStart === -1 || aliasEnd === -1) {
    throw new Error('courseInstitutionAliasMap not found');
  }
  const aliasText = source.slice(aliasStart, aliasEnd);
  const aliasRegex = /\n\s*['"]([^'\"]+)['"]\s*:\s*['"]([^'\"]+)['"]/g;
  const keys = [];
  let match;
  while ((match = aliasRegex.exec(aliasText)) !== null) {
    keys.push(match[1]);
  }
  return keys;
}

const rawCourseMap = parseRawCourses(source);
const aliasKeys = parseAliasKeys(source);
const mapKeys = Object.keys(rawCourseMap);

const requested = [
  'ACCOUNTANCY',
  'AGRICULTURAL TECHNOLOGY',
  'AGRICULTURAL ENGINEERING/TECHNOLOGY',
  'ARCHITECTURAL TECHNOLOGY',
  'ARTS AND DESIGN',
  'BANKING AND FINANCE',
  'BUILDING TECHNOLOGY',
  'BUSINESS ADMINISTRATION & MANAGEMENT',
  'CHEMICAL ENGINEERING TECHNOLOGY',
  'CIVIL ENGINEERING TECHNOLOGY',
  'COMPUTER SCIENCE',
  'COMPUTER ENGINEERING',
  'CO-OPERATIVE ECONOMICS & MANAGEMENT',
  'DENTAL TECHNOLOGY',
  'DENTAL THERAPY',
  'ELECTRICAL/ELECTRONICS ENGINEERING TECHNOLOGY',
  'ESTATE MANAGEMENT AND VALUATION',
  'FASHION DESIGN AND CLOTHING TECHNOLOGY',
  'FOOD TECHNOLOGY',
  'FORESTRY TECHNOLOGY',
  'GEOLOGICAL TECHNOLOGY',
  'GLASS/CERAMICS TECHNOLOGY',
  'HORTICULTURAL TECHNOLOGY',
  'HOSPITALITY MANAGEMENT',
  'INSURANCE',
  'LIBRARY AND INFORMATION SCIENCE',
  'LOCAL GOVERNMENT STUDIES',
  'MARINE ENGINEERING',
  'MARINE TRANSPORT & BUSINESS STUDIES',
  'MARKETING',
  'MASS COMMUNICATION',
  'MECHANICAL ENGINEERING TECHNOLOGY',
  'MECHATRONICS ENGINEERING TECHNOLOGY',
  'METALLURGICAL ENGINEERING TECHNOLOGY',
  'MINERAL RESOURCES ENGINEERING TECHNOLOGY',
  'MULTIMEDIA TECHNOLOGY',
  'MUSIC TECHNOLOGY',
  'NAUTICAL SCIENCE',
  'NURSING PROGRAMME',
  'OFFICE TECHNOLOGY AND MANAGEMENT',
  'PENSION ADMINISTRATION AND MANAGEMENT',
  'PETROLEUM ENGINEERING TECHNOLOGY',
  'PETROLEUM MARKETING AND BUSINESS STUDIES',
  'PHARMACEUTICAL TECHNOLOGY',
  'PHOTOGRAPHY',
  'PHYSICAL AND HEALTH EDUCATION',
  'POLYMER TECHNOLOGY',
  'PRINTING TECHNOLOGY',
  'PROCUREMENT AND SUPPLY CHAIN MANAGEMENT',
  'PROSTHETICS/ORTHOTICS TECHNOLOGY',
  'PUBLIC ADMINISTRATION',
  'PUBLIC HEALTH',
  'QUANTITY SURVEYING',
  'RAILWAY ENGINEERING TECHNOLOGY',
  'SCIENCE LABORATORY TECHNOLOGY',
  'SHIPPING & PORT ENGINEERING TECHNOLOGY',
  'SOCIAL DEVELOPMENT',
  'SPORTS COACHING AND TRAINING',
  'SPORTS MANAGEMENT',
  'SURVEYING AND GEO-INFORMATICS',
  'TAXATION',
  'TEXTILES TECHNOLOGY',
  'TOURISM MANAGEMENT TECHNOLOGY',
  'TRANSPORT PLANNING & MANAGEMENT',
  'TRANSPORT & LOGISTICS MANAGEMENT',
  'TRANSPORT SAFETY TECHNOLOGY',
  'URBAN AND REGIONAL PLANNING',
  'VETERINARY LABORATORY TECHNOLOGY',
  'WATER RESOURCES ENGINEERING TECHNOLOGY',
  'WELDING AND FABRICATION TECHNOLOGY',
  'WELDING ENGINEERING TECHNOLOGY',
  'WOOD AND PAPER TECHNOLOGY',
  'ACCOUNTING TECHNOLOGY',
  'AGRICULTURAL AND BIO-ENVIRONMENTAL ENGINEERING TECHNOLOGY',
  'AGRICULTURAL AND BIO-ENVIRONMENTAL ENGINEERING TECHNOLOGY (continued)',
  'AUTO BODY TECHNOLOGY',
  'AUTOMOBILE ENGINEERING',
  'AVIATION MANAGEMENT',
  'AVIATION SECURITY',
  'BOAT AND SHIP BUILDING ENGINEERING TECHNOLOGY',
  'CARTOGRAPHY AND GEOGRAPHIC INFORMATION SYSTEM',
  'CERAMICS TECHNOLOGY',
  'CIVIL AND CONSTRUCTION ENGINEERING',
  'CIVIL AND WATER RESOURCES ENGINEERING',
  'CLIMATE CHANGE SCIENCES',
  'COMMUNICATION TECHNOLOGY',
  'COMMUNITY HEALTH',
  'COMPUTER AND COMMUNICATION ENGINEERING',
  'COMPUTER AND INFORMATION SCIENCE',
  'COMPUTER SCIENCE WITH (ECONOMICS) (MATHEMATICS)',
  'COMPUTER SCIENCE WITH ACCOUNTING',
  'COMPUTER SCIENCE WITH ECONOMICS',
  'COMPUTER SCIENCE WITH ISLAMIC RELIGIOUS STUDIES',
  'COMPUTER SCIENCE WITH MATHEMATICS',
  'COMPUTER WITH STATISTICS',
  'CONSTRUCTION TECHNOLOGY EDUCATION',
  'CRIME MANAGEMENT',
  'CROP PRODUCTION TECHNOLOGY',
  'CULTURAL ADMINISTRATION AND RESOURCE MANAGEMENT',
  'CYBER SECURITY SCIENCE',
  'DENTAL SURGERY TECHNOLOGY',
  'DISPENSING OPTICIANRY',
  'ELECTRICAL ENGINEERING TECHNOLOGY',
  'ELECTRICAL TECHNOLOGY',
  'ELECTRONICS AND COMPUTER ENGINEERING',
  'ELECTRONICS AND COMPUTER SYSTEMS',
  'ELECTRONICS AND TELECOMMUNICATIONS ENGINEERING',
  'ELECTRONICS ENGINEERING',
  'ENERGY AND PETROLEUM STUDIES',
  'ENERGY STUDIES',
  'ENVIRONMENTAL ENGINEERING',
  'ENVIRONMENTAL HEALTH',
  'ENVIRONMENTAL HEALTH TECHNOLOGY',
  'ENVIRONMENTAL MANAGEMENT AND TOXICOLOGY',
  'ENVIRONMENTAL MANAGEMENT TECHNOLOGY',
  'ENVIRONMENTAL RESOURCES MANAGEMENT',
  'ENVIRONMENTAL SCIENCE AND TECHNOLOGY',
  'ENVIRONMENTAL SCIENCE MANAGEMENT',
  'ENVIRONMENTAL TECHNOLOGY',
  'EPIDEMIOLOGY AND DISEASE CONTROL',
  'EXERCISE AND SPORTS SCIENCE',
  'EXPLOSIVE ORDNANCE TECHNOLOGY',
  'FASHION DESIGN',
  'FILM AND MULTI MEDIA STUDIES',
  'FILM AND VIDEO STUDIES',
  'FILM PRODUCTION',
  'FILM STUDIES AND PRODUCTION',
  'FISHERIES AND AQUATIC TECHNOLOGY',
  'FOUNDRY ENGINEERING TECHNOLOGY',
  'GAS ENGINEERING',
  'GEOGRAPHY AND METEOROLOGY',
  'GEOGRAPHY AND PLANNING',
  'GEOGRAPHY AND REGIONAL PLANNING',
  'GEOGRAPHY/PHYSICS',
  'GEOLOGY AND MINING',
  'GEOLOGY AND MINERAL SCIENCES',
  'GEOLOGY AND PETROLEUM STUDIES',
  'GEOLOGY/GEOPHYSICS',
  'GEOSCIENCE',
  'GEOSCIENCES INFORMATION SYSTEM',
  'GRAPHICS DESIGN AND ADVERTISING',
  'HEALTH INFORMATION MANAGEMENT',
  'HEALTH INFORMATION SYSTEM',
  'HEALTH INFORMATION MANAGEMENT SYSTEM',
  'HEALTHCARE AND HOSPITAL MANAGEMENT',
  'HEALTHCARE ADMINISTRATION & HOSPITAL MANAGEMENT',
  'HIGHWAY ENGINEERING',
  'HOME AND RURAL ECONOMICS',
  'HORTICULTURE AND LANDSCAPE TECHNOLOGY',
  'HYDROLOGY AND WATER RESOURCES MANAGEMENT',
  'INDUSTRIAL AND LABOUR RELATIONS',
  'INDUSTRIAL DESIGN',
  'INDUSTRIAL MAINTENANCE ENGINEERING TECHNOLOGY',
  'INDUSTRIAL SAFETY AND ENVIRONMENTAL ENGINEERING TECHNOLOGY',
  'INFORMATION AND COMMUNICATION ENGINEERING',
  'INFORMATION AND COMMUNICATION TECHNOLOGY',
  'INFORMATION AND MEDIA SCIENCE',
  'INFORMATION AND MEDIA STUDIES',
  'INFORMATION AND MEDIA TECHNOLOGY',
  'INFORMATION RESOURCE MANAGEMENT',
  'INFORMATION SCIENCE',
  'INFORMATION SYSTEMS',
  'INFORMATION SYSTEMS AND TECHNOLOGY',
  'INFORMATION TECHNOLOGY',
  'INFORMATION TECHNOLOGY AND HEALTH INFORMATICS',
  'LAUNDRY AND DRY-CLEANING TECHNOLOGY',
  'LEATHER TECHNOLOGY',
  'MARINE GEOLOGY',
  'MARINE METEOROLOGY & COASTAL MANAGEMENT',
  'MARITIME ECONOMICS AND FINANCE',
  'MARITIME SCIENCE',
  'MARITIME TRANSPORT AND LOGISTICS',
  'MEDICAL IMAGING TECHNOLOGY'
];
const missing = requested.filter(course => !mapKeys.includes(course));
const extra = mapKeys.filter(course => !requested.includes(course));
console.log('requested', requested.length);
console.log('raw mapped', mapKeys.length);
console.log('missing', missing.length, missing);
console.log('extra raw courses', extra.length, extra);
console.log('alias keys', aliasKeys.length, aliasKeys);
